version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.3
    container_name: film-loki
    ports:
      - '3100:3100' # Loki API endpoint
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-data:/loki # Lưu data local
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - logging
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.3
    container_name: film-grafana
    ports:
      - '3001:3000' # Port 3001 để tránh conflict với NestJS
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning # Auto-config datasource
    networks:
      - logging
    depends_on:
      - loki
    restart: unless-stopped

networks:
  logging:
    driver: bridge

volumes:
  grafana-data:
