version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.3
    container_name: film-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-data:/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - logging

  grafana:
    image: grafana/grafana:10.2.3
    container_name: film-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    networks:
      - logging
    depends_on:
      - loki

  promtail:
    image: grafana/promtail:2.9.3
    container_name: film-promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - ./logs:/logs:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - logging
    depends_on:
      - loki

networks:
  logging:
    driver: bridge

volumes:
  grafana-data:
